services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: webshop
      POSTGRES_USER: webshop
      POSTGRES_PASSWORD: webshop
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
